export enum Configuration {
  PORT = 'PORT',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_SSL = 'POSTGRES_SSL',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USERNAME = 'POSTGRES_USERNAME',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DATABASE = 'POSTGRES_DATABASE',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION = 'JWT_EXPIRATION',
}
